INSERT INTO spots (id, name, lat, lng, base_point, is_secret, event_script) VALUES
('A', '博多駅クリスマスマーケット', 33.5897, 130.4207, 100, false,
  '{"title": "博多駅のイルミネーション", "dialogue": ["...わ", "...すごい、イルミネーション...きれい"], "choices": [{"text": "一緒に写真撮ろう", "points": 15, "affection": 2}, {"text": "寒くない？", "points": 10, "affection": 1}, {"text": "次行こうか", "points": -5, "affection": -1}]}'),
('B', '天神市役所前広場', 33.5902, 130.3987, 100, false,
  '{"title": "天神のクリスマスツリー", "dialogue": ["...大きいツリー", "...小樽にもあるけど...こっちの方が...なんか、あったかい感じ"], "choices": [{"text": "ホットチョコ買ってこようか？", "points": 15, "affection": 2}, {"text": "北海道のツリーはどんな感じ？", "points": 10, "affection": 1}, {"text": "人多いね", "points": 0, "affection": 0}]}'),
('C', '天神中央公園', 33.5925, 130.3952, 120, false,
  '{"title": "中央公園のイルミネーション", "dialogue": ["...ここ、静かでいいね", "...人混み、ちょっと苦手だから..."], "choices": [{"text": "ベンチで少し休もうか", "points": 15, "affection": 2}, {"text": "俺も静かな方が好き", "points": 10, "affection": 1}, {"text": "もっと賑やかな所行く？", "points": -5, "affection": -1}]}'),
('D', '旧福岡県公会堂貴賓館', 33.5942, 130.3941, 150, false,
  '{"title": "130体のサンタクロース", "dialogue": ["...えっ、サンタさんがいっぱい...", "...なまら可愛い...あっ", "...今の聞かなかったことにして..."], "choices": [{"text": "なまら可愛いね（真似）", "points": 20, "affection": 3}, {"text": "方言、可愛いと思うよ", "points": 15, "affection": 2}, {"text": "写真撮ろうか", "points": 10, "affection": 1}]}'),
('E', '大名ガーデンシティ', 33.5881, 130.3933, 100, false,
  '{"title": "大名のイルミネーション", "dialogue": ["...おしゃれな場所...", "...福岡って、都会だね"], "choices": [{"text": "かおりも街に似合ってるよ", "points": 15, "affection": 2}, {"text": "小樽とは違う？", "points": 10, "affection": 1}, {"text": "お腹空いた？", "points": 5, "affection": 0}]}'),
('F', '福岡タワー', 33.5934, 130.3515, 150, false,
  '{"title": "福岡タワーの夜景", "dialogue": ["...すごい...海が見える", "...こんな景色、初めて見た..."], "choices": [{"text": "今日、楽しかった？", "points": 20, "affection": 3}, {"text": "また来ようね", "points": 15, "affection": 2}, {"text": "寒いから降りようか", "points": -5, "affection": -1}]}'),
('S1', '櫛田神社', 33.5912, 130.4108, 200, true,
  '{"title": "櫛田神社で初詣の下見", "dialogue": ["...ここ、有名な神社なんだ", "...お正月、また来れたらいいな..."], "choices": [{"text": "一緒に来よう、約束", "points": 25, "affection": 3}, {"text": "お守り買おうか", "points": 15, "affection": 2}, {"text": "人多そうだね", "points": 0, "affection": 0}]}'),
('S2', '警固神社', 33.5886, 130.3986, 200, true,
  '{"title": "警固神社の静けさ", "dialogue": ["...天神にこんな静かな場所があるんだ", "...落ち着く..."], "choices": [{"text": "二人だけの秘密の場所だね", "points": 25, "affection": 3}, {"text": "お参りしていこう", "points": 15, "affection": 2}, {"text": "次行こうか", "points": -5, "affection": -1}]}'),
('S3', '中洲屋台街', 33.5945, 130.4045, 200, true,
  '{"title": "屋台でラーメン", "dialogue": ["...屋台...初めて", "...ラーメン、おいしい...", "...福岡、好きになっちゃった...かも"], "choices": [{"text": "俺も、かおりが来てくれて嬉しい", "points": 25, "affection": 3}, {"text": "替え玉する？", "points": 10, "affection": 1}, {"text": "そろそろ帰ろうか", "points": 0, "affection": 0}]}');
